<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <RootNamespace>FSB_helper_C__</RootNamespace>
    <Nullable>disable</Nullable>
    <OutputPath>bin\Build</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <PublishDir>bin\Build</PublishDir>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>DURANHELPER</AssemblyName>
    <Product>DURAN HELPER</Product>
    <UseWPF>true</UseWPF>
    <Title>DURAN HELPER</Title>
    <UseWindowsForms>true</UseWindowsForms>
    <Version>4.0.0</Version>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <None Update="DuranOverlay.asi">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>